language: node_js
node_js: 6
sudo: required
git:
  depth: 5
branches:
  only:
  - "/^(?i:SWIK)-.*$/"
  - master
cache:
  directories:
  - "./application/node_modules"
before_install:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then ./travis_scripts/install_compose.sh ; fi
- cd application
script:
- sleep 15
- npm run lint
after_success:
- cd ..
- openssl aes-256-cbc -K $encrypted_9e8bcb5f7516_key -iv $encrypted_9e8bcb5f7516_iv -in deployment_keys.tar.enc -out deployment_keys.tar -d
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then ./travis_scripts/dockerhub.sh ; fi
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then ./travis_scripts/deploy.sh ; fi
- cd application
after_script:
- npm run coverall
- rm -f deployment_keys.tar
- rm -f ~/.docker/{cert.pem,key.pem,ca.pem,config.json}
services:
- docker
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: qPAjYvVfyiiEYSrP4JnV/vSVRTGvETFdTGBb/TuLVynk84sOoH048udo1johLFCUALsmK7n11Nh9y2ehHo+jexH7UCzGHb4g7CJCNCa/EOIygMTbsntyspB2tCMAQbgf/hUMjGQrjqrysrvu21THhms2lRZ+fKFwmpI0xd+6MsSRVLjF95xl7gVC8ikIkUck27ZxcEOYhf3RK/tnPdbHjPu+dWSPkH7zVwLq3SvypRn7fwK9TDEo8VvXCNOF+6MX9KquCi251+0ZNTHKkiGkyqoz07tWPmaXuvf6v22XKZO8zWcDkA6qVtYheXkMYPl8cl0YAs5U7PwQz+mZhKQDbMoltj/NosKiKAtZk4Fg7ALweZE4wcIggfAhSe052ImgI06vtb1O6hVzGVxynT1vVISrPUymh2yNI/pJ1P/eHtFWg5TO+rxNHJSQYTWWRLxjEvgolDSpdOikDLRt/GrE7qkvqv0ONNPrxf2/bZBQaT27ALN/CWz5KiGAGSq8dilwiIBjUBRJCDgnmZQsa2p3kFUti7+TjMB0NhSpNc6ht8zje7lL5DSUMx6VgbOoVK3cK4zpKsiLfOgnWU0AKQWohaNCDoNe3JxZl+pINUy4sSDq/dDaDOC4wSn3p4zKD/ryJoftkzEHTQFy9HC8epgU1s3xXFCN3d9u2KblWnCCiCc=
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.6.2
  - secure: YfdAz3IEFOI0LacKaJh95yHW6uOfWjh6CHFyTJ3/3oo8jJuq2jwI2M1+W+AbwzzR/NC0ppiimIkjREl9FUUw3YcHZRexxNcx3qGQQtTGmMDL2TdLESciPG2fvEdxK2uJzOItMEOQXJoaSDApWzjyCAwAELKKWcvptSLAtFxfUjvDgA9nrwtlUXSKt3b2bgqTpPhpcX2px1lWgZCeO2ggUqTentSGuMFYHbQ4k1M47eY9Hk3hWHDJZ6vNJrlLUvCA9nqjaQH8F5IqTbjFVwwYCfDYXRR3RFlUr0EoMDpu7D1n6KgMN/2KhlSLz+E7pvRY74z188qHmrRWFc0QPteBndqJvz2y8Uc4vYa4Z/9o+pQf7Uur4/3xqGCtkd/reuAZSK0fja8PZm5zPsVMb/v3xEZbpWX+f2+cGVyBiIUowWkyd0I+J8M62v/pPYfCz9q6Ok+umexANzVOPlMGa75PEdsiTZgPaYO8Q85VD43szR743N8xTRVZtCXudyvYoxxyhIZmww91WgsD4cFoW7qp14aV9JwZk1PtJYIs1VfzG7fFLk5YxvLld/eFQZRSqwoJ91QuikzaxM05ECoB9zwzsMR23oXZP+0xpYN4zWzaVDGoMVfbNfAPQIJOsgjTNsLFdCiuxAF4KU+l3UiBpHnTLQhIf5RErjQpCGYWt/Dpim4=
  - secure: Dskfl/ouQzHG84j6/6YvUlvK+5d2CHczB/kCDfeBbUKVRS9lsu1iuZD7LhRB+rFd2+wDF9vCoAbUMoasqLYOvuSrFUK6FYx1WZsOTMBc6QyKpu5jsyzHFVul5EzSgMzx8KPeiylJxWLy5/7CwYEJcfKcAnUcFhRpkpHJA+EJkHKeXESTzOraUMXmPwWhWgoIbP/RVloDFGzlRffnt6ieSSPqRMCFvoDoU3RUftj1l8ywOukJ4Cb5FLpZ0QM7E8WbCISjyRA23+90ek3bhQdoNbrMXXlCcVeJbns3lzPggzdtGLIgQdXG4boQDfUt33R80BPSvMLqED8DniFSu6Rz0LN503w4x0M/sOOV0RQyiSoh6Wdk4N2kyRI8hDDa2+NrvYBRp+n7AIel3il8QkH/y4Md2RluJa12L4Ghdko5M1oCb93nXUAO4sAh4lzNu7922weNG2GAuTNGb9gAa3073JvHFF5dbQTlSLlmDAGE4+aUnfidHZiLaHENZrnQg7Bj71eGX9cC8g3F+XGNF6TlYK87qog6/Qn8jP3TI2pSw5IDply9lXJujBB3mJIGpTjxLxLlEgXogm+xXstlqX8K+J/nic+RUHkH0Pmr6HDDmW1soDInZuZKDofOmRLBYS8ko9RTYswKi64WpDlIAZTABgThVj9OiNql2DVLCGEbPvk=
  - secure: vXIolFkQbUajaNo4Cj07ixRWoYV8RnpTS3WocLFa6vcoiCxmUpTsMvfUNRzpWI66oJ7DDlsy7VCISFOOgl68/YLRDaqV5LutKiafjo9uoRcLNJAMnt3reX0oS08Hdu0xCH1vqUXRerh4F12mA/3p7v14S9pH7CBocFr57mjgiHfq2itmsFHxB7Eny59I8u/7kk1uLKrkqhdK1SX/W0aapPiwmotUkOYxepnqk9d3SE2mF/ZVw9RuVS7P6HQ7xEVGcXu9+IvcEVPQwyAILrN4FNYUWr/t4KSbFIpVFfjf9943Rm87qvRWWt/lVVvbF6E0a9Ok8Mw/NbwSAfTo8iA0E6YzQtJjiK+/b/Ku50RMKEhP1BRamvp/t1seKOfJ0aPIarzCiW1WJMbZlC80QUI9E2ynta4meN0G8Yfc1+v6rIrd5zpkPi6n3g0HXoypd60j5s4QjC2vHeaACxOoeG/HyiXTff9Hjbh+0wu0dz4tT7014zcy4IXaAUuBwWwRAmE7XmrVtqWHpn5bWfZ9tW03HQa21KCWXnrtQIFTyWq/+nA3z8UG3k0ABrJTeb6P+fYiUcy3+j87HWn+VSEKsqAevKO6dAJdd/7jfT2yVxJig9BOhR97nOVAsS9hWcFsvW80m5uUyiITpEaWEdiDS1lyhXIQptdsD/3bVLf0Z+absbk=
  - secure: Y7gwDi/EEp7vXY5jvBF/D4DflInWsxw2k2VRbfUiTzmcAmkmAu61j7ceStfRJMp9apMIRzxmSSHzdwYLo069cygMnWEo4C0+WqIT1Vkwi+TbPyMN/8rf98FPW2KD3m8PDevRa+gC2he8aSmeKN4OxfuE6ULT0nVo4/rJlQ7WrOBFqEZ+KmyFIUV/RQyYf2K6CvFkUNbh/fqgA1dUFv5Zbgr4XYN5DSj2eIruc8G0pX4Eyiu+t28qI3p91aJkiRYv/qAU4aC8ANV+pJCmqnqaoNlKRCkEn4pyrB7aLdzsf+2VygOAqYfO59Sb1C4sNeDFQ6idfix4TmqFNVvfBSWGzErU+9NJyGWazyCoJPm+SBLWEZwxJs0CV9mgNyDFa8i59VmQzC4e898Ww56CVS32jx/t6Aa+uf0/DbJb4Z/Plz+JWa2feDTmudI5QDkBDiudH4uewuwf86GfjnOENatl7ayVR3oEhQM4AavBfnLrKnAlTEkA+p1CeYw1Fmd9penuOxOS/NPHWOyrfZYBNhiM7WgALOj0TNZnRxePI754ts1nEM3SGumuoa4wlQNB1BbJOK7vUbsjTwm37SDbd9Am7FmzgexOy/UVwm4WHziX6NZvd+hjU/1uxRjCZBrKrkwvz6GA2oiZJO2va80t6sNnk5GeOGPOwpJ3oBsMB/hxX5c=
