language: node_js
node_js: 6
sudo: required
git:
  depth: 5
branches:
  only:
  - "/^(?i:SWIK)-.*$/"
  - master
cache:
  directories:
  - "./application/node_modules"
before_install:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then ./travis_scripts/install_compose.sh ; fi
- cd application
script:
- sleep 15
- npm run lint
after_success:
- cd ..
- openssl aes-256-cbc -K $encrypted_9e8bcb5f7516_key -iv $encrypted_9e8bcb5f7516_iv -in deployment_keys.tar.enc -out deployment_keys.tar -d
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then ./travis_scripts/dockerhub.sh ; fi
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then ./travis_scripts/deploy.sh ; fi
- cd application
after_script:
- npm run coverall
- rm -f deployment_keys.tar
- rm -f ~/.docker/{cert.pem,key.pem,ca.pem,config.json}
services:
- docker
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: qPAjYvVfyiiEYSrP4JnV/vSVRTGvETFdTGBb/TuLVynk84sOoH048udo1johLFCUALsmK7n11Nh9y2ehHo+jexH7UCzGHb4g7CJCNCa/EOIygMTbsntyspB2tCMAQbgf/hUMjGQrjqrysrvu21THhms2lRZ+fKFwmpI0xd+6MsSRVLjF95xl7gVC8ikIkUck27ZxcEOYhf3RK/tnPdbHjPu+dWSPkH7zVwLq3SvypRn7fwK9TDEo8VvXCNOF+6MX9KquCi251+0ZNTHKkiGkyqoz07tWPmaXuvf6v22XKZO8zWcDkA6qVtYheXkMYPl8cl0YAs5U7PwQz+mZhKQDbMoltj/NosKiKAtZk4Fg7ALweZE4wcIggfAhSe052ImgI06vtb1O6hVzGVxynT1vVISrPUymh2yNI/pJ1P/eHtFWg5TO+rxNHJSQYTWWRLxjEvgolDSpdOikDLRt/GrE7qkvqv0ONNPrxf2/bZBQaT27ALN/CWz5KiGAGSq8dilwiIBjUBRJCDgnmZQsa2p3kFUti7+TjMB0NhSpNc6ht8zje7lL5DSUMx6VgbOoVK3cK4zpKsiLfOgnWU0AKQWohaNCDoNe3JxZl+pINUy4sSDq/dDaDOC4wSn3p4zKD/ryJoftkzEHTQFy9HC8epgU1s3xXFCN3d9u2KblWnCCiCc=
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.6.2
  - secure: ALawyCVulz0Hy0DADAw4z3Ab+ydHvw4tYoyYoN+zz1cMrjWKWzDuIvCq0jqmHICgq6o9kPJWfyUPbXzxDON8vJj37OHbZyh0LnNU0glmnZE6Zo1cql6GEZ1WoOYGZp9p3rlKSAFVS1mCxWA9YYUPReEb/cRowgVJT2oVwPlblv6b1znxqzBMltf1M2IuLYFDPbgNRPTJJliDu6KLmp2/pHftjCcR7zm12ea1fkphe1hfQgByq3riIYLTDE5Xzl5QAIRrQqxEZzwn5E0g3LYsql20jjbRUAXZ1chUuXl4q6u9f9L/IX4XLduIrAcjORapFio3J0poKueTKKmVRxmnTTz0v/6xUD72vI1omPp2I/blkSoyClSjLtrhSXmVthAoe7ixQ43IsYHS/+A1Z6nWcgY8OCQRCBzmRyOJWYs/awzL9vvGsdkhGRLvcDp3mih/GFSLuMOPuRoXf/4A0j7rD7NpkpWDqVbow65SM1HPf0HMuSdUu+ciFTeAGylkEDrUYAwyttVcyPD/Tq+3tSzFLco/INFx7OLA8ztbZLu+3m/kCOhoiqu0PXqYNNcS+h4ZXGqs+NRYAbYulb7IWLwews78pJY0xzu3dhfvBVTuXLOrmP2WZ0t9LAhP7iHZZbBx00Or/L5uenDMqU09V9Abs3Bxx3ozm9SruBoWk78BeUo=
  - secure: P+YE1i7GMtNKBWHKGI1Cv6DMpl3dBy6FOx/Sf/FPxowPLrkoKLeye9lJsi0Uu83UpSYXNJjkMrDi7oIgVuezTCw9ZMvQ746aNK82cv8epMaKjhdmfCcjKsHwNALHL8wnMZPBb4W6ExJqVTq0tsPUU4XqjySrnavu+MfAjhrYva8yGhL8Y7nh27FUoGyLVy4y1zbNCHJkfQAQrysSqlI/TjKwxtGcQIzspkY7sXhYWtYrl26JMVfZ5nbQU1mlRwuBKmMJK5u/LPizSLPOhXOaEAu3L8N5ybKa7pFCiV0YogLD1Ned+181LmIM3VYPPiIYqAoxfWrRBJOyjQdVSbl78dn8CS3Nuo7wHttuF+/+2FkyCyM+nk/4hZe0B37ULBpyLSQyHq3iGc6+nKenvS1AxeDy3NzK8tw/anmflJsUhyxFlQcUsmWYA9dsDRIZ8Kd0BCVv6frZPrZVYZ5GZX0kvDpTFlK2kP2/POR/2TrlXZCP3evPGNEvz7QhSsuL1EL9Uog5/RrdcIUoITZAvnSPauO1m6HtAKeFG77VqcUFuxs7ZkBAd1sMjXM+wDj68ywSNul1qssI0Y3rgKbZf6KRnvWcC7NVyfjOnKvQXb3/QiJw6Oqm5CginkW4eH3EYH30fBfBvS9iYgNKhE1q20PJ8y4I/jLqG2Nd3dc5NN7rXK8=
  - secure: jey9+ZQnmm4IO7zTqRiuLX5y0t18u3B6q28RyLI69yomJ6qvvksGDM67tdzCeKYoXNZ/BX4edvMatXxwGpaBSZggwAidw4lc4neaOyw3J+XRZLI6OSM47KimAJeBgQoXussTf5uU/TsAgnH4CnxMxJocbp+K37IXRMNZxRIQOXMcCirJoroy766tVb5yjilSPS1SfMgI5akaVwr1xfAYPQOesd5rq9wHlZCzooY4q8A1ODSGw7x5UgzEmPKrAfLl3Pk2UlBoQFaAsT8hwFqk3iVCBO7mDKRSzQrtUDl536jVnGX1idwkG+1KhptRlAzWc5Pc9oQWep1esMH4/veJm1OzDK+IbXci1Hp6dV9v2cF6atcV7Qgp2u3Q58bifZd1YHzWu/mf+82bg5WhoM5tolnXvi5kLHaO0bPV2z4mBbEAUgblPJ5bLvxAQed8AnzyDs1M9lr3LgPymwzYuH4KDsz07fh2JA69WjVWI2Vm/yqUmvEP7PZBUUXu0SKbWnxFROdbOLjjXZtOflCC6UgV1Wk/HqlF58sMLT0XZtqECVdV8EduYDux0TPy5sxH3qPPHH0PNKypiuV4ThNSQYPTHTG6ZoBA2PWwVsJF0mRVjRxBU+NDexQ8FOm2aw5Jks8J3DwiFzLQrGO5XDwkra2MfLy8k9EzS/3Ij9ViuhTsRTI=
