fileservice:
  image: slidewiki/fileservice
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - APPLICATION_PATH=/data/files
    - VIRTUAL_HOST=fileservice.experimental.slidewiki.org
    - DATABASE_URL=mongodb # use a url or the name, defined in the docker-compose file
    - LETSENCRYPT_HOST=fileservice.experimental.slidewiki.org
    - LETSENCRYPT_EMAIL=meissner@informatik.uni-leipzig.de
  external_links:
    - mongodb
  volumes:
    - files:/data/files
