template:
  image: slidewiki/fileservice
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - APPLICATION_PORT=8080
    - APPLICATION_PATH=/data/files
    - VIRTUAL_HOST=fileservice.manfredfris.ch
