fileservice:
#  image: slidewiki/fileservice
  build: ./
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - APPLICATION_PORT=80
    - APPLICATION_PATH=/data/files
    - VIRTUAL_HOST=fileservice.manfredfris.ch
  volumes:
    - /data/files:/data/files:ro
