fileservice:
  image: slidewiki/fileservice
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - APPLICATION_PATH=/data/files
    - VIRTUAL_HOST=fileservice.experimental.slidewiki.org
  volumes_from:
    - datapod
